insert into pais (sigla, nome) values ('AD','Andorra')
insert into pais (sigla, nome) values ('AE','Emirados Árabes Unidos')
insert into pais (sigla, nome) values ('AF','Afeganistão')
insert into pais (sigla, nome) values ('AG','Antígua e Barbuda')
insert into pais (sigla, nome) values ('AI','Anguilla')
insert into pais (sigla, nome) values ('AL','Albânia')
insert into pais (sigla, nome) values ('AM','Armênia')
insert into pais (sigla, nome) values ('AN','Antilhas Holandesas')
insert into pais (sigla, nome) values ('AO','Angola')
insert into pais (sigla, nome) values ('AP','Organização Regional de Propriedade Industrial Africana')
insert into pais (sigla, nome) values ('AQ','Antartica')
insert into pais (sigla, nome) values ('AR','Argentina')
insert into pais (sigla, nome) values ('AS','Samoa Americana')
insert into pais (sigla, nome) values ('AT','Áustria')
insert into pais (sigla, nome) values ('AU','Austrália')
insert into pais (sigla, nome) values ('AW','Aruba')
insert into pais (sigla, nome) values ('AZ','Azerbaidjão')
insert into pais (sigla, nome) values ('BA','Bósnia e Herzegóvina')
insert into pais (sigla, nome) values ('BB','Barbados')
insert into pais (sigla, nome) values ('BD','Bangladesh')
insert into pais (sigla, nome) values ('BE','Bélgica')
insert into pais (sigla, nome) values ('BF','Burkina Faso')
insert into pais (sigla, nome) values ('BG','Bulgária')
insert into pais (sigla, nome) values ('BH','Bareine')
insert into pais (sigla, nome) values ('BI','Burundi')
insert into pais (sigla, nome) values ('BJ','Benin')
insert into pais (sigla, nome) values ('BM','Bermudas')
insert into pais (sigla, nome) values ('BN','Brunei Darussalam')
insert into pais (sigla, nome) values ('BO','Bolívia')
insert into pais (sigla, nome) values ('BR','Brasil')
insert into pais (sigla, nome) values ('BS','Bahamas')
insert into pais (sigla, nome) values ('BT','Butão')
insert into pais (sigla, nome) values ('BV','Ilha Bouvet')
insert into pais (sigla, nome) values ('BW','Botswana')
insert into pais (sigla, nome) values ('BX','Benelux')
insert into pais (sigla, nome) values ('BY','Belarus')
insert into pais (sigla, nome) values ('BZ','Belize')
insert into pais (sigla, nome) values ('CA','Canadá')
insert into pais (sigla, nome) values ('CC','Ilhas Cocos')
insert into pais (sigla, nome) values ('CD','República Dem. Do Congo')
insert into pais (sigla, nome) values ('CF','República Centro Africana')
insert into pais (sigla, nome) values ('CG','Congo')
insert into pais (sigla, nome) values ('CH','Suíça')
insert into pais (sigla, nome) values ('CI','Costa do Marfim')
insert into pais (sigla, nome) values ('CK','Ilhas Cook')
insert into pais (sigla, nome) values ('CL','Chile')
insert into pais (sigla, nome) values ('CM','Camarões')
insert into pais (sigla, nome) values ('CN','China')
insert into pais (sigla, nome) values ('CO','Colômbia')
insert into pais (sigla, nome) values ('CR','Costa Rica')
insert into pais (sigla, nome) values ('CU','Cuba')
insert into pais (sigla, nome) values ('CV','Cabo Verde')
insert into pais (sigla, nome) values ('CX','Ilha Natal')
insert into pais (sigla, nome) values ('CY','Chipre')
insert into pais (sigla, nome) values ('CZ','República Tcheca')
insert into pais (sigla, nome) values ('DE','Alemanha')
insert into pais (sigla, nome) values ('DJ','Djibuti')
insert into pais (sigla, nome) values ('DK','Dinamarca')
insert into pais (sigla, nome) values ('DM','Dominica')
insert into pais (sigla, nome) values ('DO','República Dominicana')
insert into pais (sigla, nome) values ('DZ','Argélia')
insert into pais (sigla, nome) values ('EC','Equador')
insert into pais (sigla, nome) values ('EE','Estônia')
insert into pais (sigla, nome) values ('EG','Egito')
insert into pais (sigla, nome) values ('EH','Saara Ocidental')
insert into pais (sigla, nome) values ('EM','Escritório para Harmonização no Mercado Interno')
insert into pais (sigla, nome) values ('ER','Eritréia')
insert into pais (sigla, nome) values ('ES','Espanha')
insert into pais (sigla, nome) values ('ET','Etiópia')
insert into pais (sigla, nome) values ('FI','Finlândia')
insert into pais (sigla, nome) values ('FJ','Fiji')
insert into pais (sigla, nome) values ('FK','Ilhas Malvinas')
insert into pais (sigla, nome) values ('FM','Micronésia')
insert into pais (sigla, nome) values ('FO','Ilhas Faroe')
insert into pais (sigla, nome) values ('FR','França')
insert into pais (sigla, nome) values ('GA','Gabão')
insert into pais (sigla, nome) values ('GB','Reino Unido')
insert into pais (sigla, nome) values ('GD','Granada')
insert into pais (sigla, nome) values ('GE','Geórgia')
insert into pais (sigla, nome) values ('GG','Ilhas do Canal')
insert into pais (sigla, nome) values ('GH','Gana')
insert into pais (sigla, nome) values ('GI','Gibraltar')
insert into pais (sigla, nome) values ('GL','Groenlândia')
insert into pais (sigla, nome) values ('GM','Gambia')
insert into pais (sigla, nome) values ('GN','Guine')
insert into pais (sigla, nome) values ('GP','Guadalupe')
insert into pais (sigla, nome) values ('GQ','Guine Equatorial')
insert into pais (sigla, nome) values ('GR','Grécia')
insert into pais (sigla, nome) values ('GS','Geórgia do Sul e Ilhas Sandwich do Sul')
insert into pais (sigla, nome) values ('GT','Guatemala')
insert into pais (sigla, nome) values ('GU','Guam')
insert into pais (sigla, nome) values ('GW','Guiné Bissau')
insert into pais (sigla, nome) values ('GY','Guiana')
insert into pais (sigla, nome) values ('HK','Hong-Kong')
insert into pais (sigla, nome) values ('HM','Ilhas Heard e McDonald')
insert into pais (sigla, nome) values ('HN','Honduras')
insert into pais (sigla, nome) values ('HR','Croácia')
insert into pais (sigla, nome) values ('HT','Haiti')
insert into pais (sigla, nome) values ('HU','Hungria')
insert into pais (sigla, nome) values ('ID','Indonésia')
insert into pais (sigla, nome) values ('IE','Irlanda')
insert into pais (sigla, nome) values ('IL','Israel')
insert into pais (sigla, nome) values ('IM','Ilha do Homem')
insert into pais (sigla, nome) values ('IN','India')
insert into pais (sigla, nome) values ('IO','Territ.Britan.Oceano Índico')
insert into pais (sigla, nome) values ('IQ','Iraque')
insert into pais (sigla, nome) values ('IR','Irã')
insert into pais (sigla, nome) values ('IS','Islândia')
insert into pais (sigla, nome) values ('IT','Itália')
insert into pais (sigla, nome) values ('JE','Jersey')
insert into pais (sigla, nome) values ('JM','Jamaica')
insert into pais (sigla, nome) values ('JO','Jordânia')
insert into pais (sigla, nome) values ('JP','Japão')
insert into pais (sigla, nome) values ('KE','Quênia')
insert into pais (sigla, nome) values ('KG','Quirguistão')
insert into pais (sigla, nome) values ('KH','Camboja')
insert into pais (sigla, nome) values ('KI','Kiribati')
insert into pais (sigla, nome) values ('KM','Comores')
insert into pais (sigla, nome) values ('KN','São Cristovão e Nevis')
insert into pais (sigla, nome) values ('KP','República Pop. Dem. da Coreia')
insert into pais (sigla, nome) values ('KR','República da Coréia')
insert into pais (sigla, nome) values ('KW','Kuwait')
insert into pais (sigla, nome) values ('KY','Ilhas Cayman')
insert into pais (sigla, nome) values ('KZ','Cazaquistão')
insert into pais (sigla, nome) values ('LA','Laos')
insert into pais (sigla, nome) values ('LB','Líbano')
insert into pais (sigla, nome) values ('LC','Santa Lúcia')
insert into pais (sigla, nome) values ('LI','Liechtenstein')
insert into pais (sigla, nome) values ('LK','Sri Lanka')
insert into pais (sigla, nome) values ('LR','Libéria')
insert into pais (sigla, nome) values ('LS','Lesoto')
insert into pais (sigla, nome) values ('LT','Lituânia')
insert into pais (sigla, nome) values ('LU','Luxemburgo')
insert into pais (sigla, nome) values ('LV','Letônia')
insert into pais (sigla, nome) values ('LY','Líbia')
insert into pais (sigla, nome) values ('MA','Marrocos')
insert into pais (sigla, nome) values ('MC','Mônaco')
insert into pais (sigla, nome) values ('MD','República da Moldova')
insert into pais (sigla, nome) values ('ME','Montenegro')
insert into pais (sigla, nome) values ('MG','Madagascar')
insert into pais (sigla, nome) values ('MH','Ilhas Marshall')
insert into pais (sigla, nome) values ('MK','República da Macedonia')
insert into pais (sigla, nome) values ('ML','Mali')
insert into pais (sigla, nome) values ('MM','Mianmá')
insert into pais (sigla, nome) values ('MN','Mongólia')
insert into pais (sigla, nome) values ('MO','Macau')
insert into pais (sigla, nome) values ('MP','Ilhas Marianas do Norte')
insert into pais (sigla, nome) values ('MQ','Martinica')
insert into pais (sigla, nome) values ('MR','Mauritânia')
insert into pais (sigla, nome) values ('MS','Mont Serrat')
insert into pais (sigla, nome) values ('MT','Malta')
insert into pais (sigla, nome) values ('MU','Maurício')
insert into pais (sigla, nome) values ('MV','Maldivas')
insert into pais (sigla, nome) values ('MW','Malawi')
insert into pais (sigla, nome) values ('MX','México')
insert into pais (sigla, nome) values ('MY','Malásia')
insert into pais (sigla, nome) values ('MZ','Moçambique')
insert into pais (sigla, nome) values ('NA','Namíbia')
insert into pais (sigla, nome) values ('NC','Nova Caledônia')
insert into pais (sigla, nome) values ('NE','Níger')
insert into pais (sigla, nome) values ('NF','Ilha Norfalk')
insert into pais (sigla, nome) values ('NG','Nigéria')
insert into pais (sigla, nome) values ('NI','Nicarágua')
insert into pais (sigla, nome) values ('NL','Holanda')
insert into pais (sigla, nome) values ('NO','Noruega')
insert into pais (sigla, nome) values ('NP','Nepal')
insert into pais (sigla, nome) values ('NR','Nauru')
insert into pais (sigla, nome) values ('NZ','Nova Zelândia')
insert into pais (sigla, nome) values ('OA','Organização Africana de Propriedade Intelectual (OAPI)')
insert into pais (sigla, nome) values ('OM','Omã')
insert into pais (sigla, nome) values ('PA','Panamá')
insert into pais (sigla, nome) values ('PE','Peru')
insert into pais (sigla, nome) values ('PF','Polinésia Francesa')
insert into pais (sigla, nome) values ('PG','Papua Nova Guiné')
insert into pais (sigla, nome) values ('PH','Filipinas')
insert into pais (sigla, nome) values ('PK','Paquistão')
insert into pais (sigla, nome) values ('PL','Polônia')
insert into pais (sigla, nome) values ('PM','Saint Pierre e Miquelon')
insert into pais (sigla, nome) values ('PN','Pitcairn')
insert into pais (sigla, nome) values ('PR','Porto Rico')
insert into pais (sigla, nome) values ('PS','Território Ocupado Palestino')
insert into pais (sigla, nome) values ('PT','Portugal')
insert into pais (sigla, nome) values ('PW','Palau')
insert into pais (sigla, nome) values ('PY','Paraguai')
insert into pais (sigla, nome) values ('QA','Catar')
insert into pais (sigla, nome) values ('RE','Reunião')
insert into pais (sigla, nome) values ('RO','Romênia')
insert into pais (sigla, nome) values ('RS','Sérvia')
insert into pais (sigla, nome) values ('RU','Federação Russa')
insert into pais (sigla, nome) values ('RW','Ruanda')
insert into pais (sigla, nome) values ('SA','Arábia Saudita')
insert into pais (sigla, nome) values ('SB','Ilhas Salomão')
insert into pais (sigla, nome) values ('SC','Seychelles')
insert into pais (sigla, nome) values ('SD','Sudão')
insert into pais (sigla, nome) values ('SE','Suécia')
insert into pais (sigla, nome) values ('SG','Singapura')
insert into pais (sigla, nome) values ('SH','Santa Helena')
insert into pais (sigla, nome) values ('SI','Eslovenia')
insert into pais (sigla, nome) values ('SJ','Svalbard e Jan Mayen')
insert into pais (sigla, nome) values ('SK','Eslováquia')
insert into pais (sigla, nome) values ('SL','Serra Leoa')
insert into pais (sigla, nome) values ('SM','São Marino')
insert into pais (sigla, nome) values ('SN','Senegal')
insert into pais (sigla, nome) values ('SO','Somália')
insert into pais (sigla, nome) values ('SR','Suriname')
insert into pais (sigla, nome) values ('ST','São Tomé e Príncipe')
insert into pais (sigla, nome) values ('SV','El Salvador')
insert into pais (sigla, nome) values ('SY','Síria')
insert into pais (sigla, nome) values ('SZ','Suazilândia')
insert into pais (sigla, nome) values ('TC','Ilhas Turks e Caicos')
insert into pais (sigla, nome) values ('TD','Chade')
insert into pais (sigla, nome) values ('TF','Terras Austrais Francesas')
insert into pais (sigla, nome) values ('TG','Togo')
insert into pais (sigla, nome) values ('TH','Tailândia')
insert into pais (sigla, nome) values ('TJ','Tadjiquistão')
insert into pais (sigla, nome) values ('TK','Tokelau')
insert into pais (sigla, nome) values ('TL','Timor-Leste')
insert into pais (sigla, nome) values ('TM','Turcomenistão')
insert into pais (sigla, nome) values ('TN','Tunísia')
insert into pais (sigla, nome) values ('TO','Tonga')
insert into pais (sigla, nome) values ('TR','Turquia')
insert into pais (sigla, nome) values ('TT','Trinidad e Tobago')
insert into pais (sigla, nome) values ('TV','Tuvalu')
insert into pais (sigla, nome) values ('TW','Taiwan')
insert into pais (sigla, nome) values ('TZ','República Unida da Tanzânia')
insert into pais (sigla, nome) values ('UA','Ucrânia')
insert into pais (sigla, nome) values ('UG','Uganda')
insert into pais (sigla, nome) values ('UM','Ilhas Menores')
insert into pais (sigla, nome) values ('US','Estados Unidos da América')
insert into pais (sigla, nome) values ('UY','Uruguai')
insert into pais (sigla, nome) values ('UZ','Uzbequistão')
insert into pais (sigla, nome) values ('VA','Vaticano')
insert into pais (sigla, nome) values ('VC','São Vicente e Granadinas')
insert into pais (sigla, nome) values ('VE','Venezuela')
insert into pais (sigla, nome) values ('VG','Ilhas Virgens (Britânicas)')
insert into pais (sigla, nome) values ('VI','Ilhas Virgens (U.S.)')
insert into pais (sigla, nome) values ('VN','Vietnã')
insert into pais (sigla, nome) values ('VU','Vanuatu')
insert into pais (sigla, nome) values ('WF','Ilhas Wallis e Futura')
insert into pais (sigla, nome) values ('WO','Organização Mundial de Propriedade Intelectual – OMPI (WIPO)')
insert into pais (sigla, nome) values ('WS','Samoa Ocidental')
insert into pais (sigla, nome) values ('WW','Teste')
insert into pais (sigla, nome) values ('YE','Iêmen')
insert into pais (sigla, nome) values ('YU','Yugoslávia')
insert into pais (sigla, nome) values ('ZA','Africa do Sul')
insert into pais (sigla, nome) values ('ZM','Zâmbia')
insert into pais (sigla, nome) values ('ZR','Zaire')
insert into pais (sigla, nome) values ('ZW','Zimbábue')