--como não deixei fixo o id do estado e pais, então segue um gato para poder buscar o id do 
--estado e executar o script corretamente

declare @id_estado int
select	@id_estado = id_estado
from	estado uf
inner	join pais pa on pa.id_pais = uf.id_pais
where	pa.sigla = 'BR' and uf.sigla = 'SP'

insert into cidade (nome, codigo_ibge, id_estado) values ('ADAMANTINA','3500105',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ADOLFO','3500204',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AGUAÍ','3500303',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁGUAS DA PRATA','3500402',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁGUAS DE LINDÓIA','3500501',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁGUAS DE SANTA BÁRBARA','3500550',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁGUAS DE SÃO PEDRO','3500600',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AGUDOS','3500709',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALAMBARI','3500758',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALFREDO MARCONDES','3500808',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALTAIR','3500907',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALTINÓPOLIS','3501004',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALTO ALEGRE','3501103',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALUMÍNIO','3501152',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁLVARES FLORENCE','3501202',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁLVARES MACHADO','3501301',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÁLVARO DE CARVALHO','3501400',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ALVINLÂNDIA','3501509',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AMERICANA','3501608',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AMÉRICO BRASILIENSE','3501707',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AMÉRICO DE CAMPOS','3501806',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AMPARO','3501905',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ANALÂNDIA','3502002',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ANDRADINA','3502101',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ANGATUBA','3502200',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ANHEMBI','3502309',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ANHUMAS','3502408',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('APARECIDA','3502507',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('APARECIDA D''OESTE','350@id_estado06',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('APIAÍ','3502705',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARAÇARIGUAMA','3502754',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARAÇATUBA','3502804',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARAÇOIABA DA SERRA','3502903',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARAMINA','3503000',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARANDU','3503109',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARAPEÍ','3503158',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARARAQUARA','3503208',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARARAS','3503307',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARCO-ÍRIS','3503356',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AREALVA','3503406',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AREIAS','3503505',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AREIÓPOLIS','3503604',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARIRANHA','3503703',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARTUR NOGUEIRA','3503802',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ARUJÁ','3503901',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ASPÁSIA','3503950',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ASSIS','3504008',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ATIBAIA','3504107',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AURIFLAMA','3504206',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AVAÍ','3504305',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AVANHANDAVA','3504404',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('AVARÉ','3504503',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BADY BASSITT','3504602',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BALBINOS','3504701',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BÁLSAMO','3504800',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BANANAL','3504909',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARÃO DE ANTONINA','3505005',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARBOSA','3505104',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARIRI','3505203',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARRA BONITA','3505302',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARRA DO CHAPÉU','3505351',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARRA DO TURVO','3505401',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARRETOS','3505500',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARRINHA','3505609',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BARUERI','3505708',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BASTOS','3505807',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BATATAIS','3505906',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BAURU','3506003',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BEBEDOURO','3506102',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BENTO DE ABREU','3506201',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BERNARDINO DE CAMPOS','3506300',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BERTIOGA','3506359',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BILAC','3506409',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BIRIGÜI','3506508',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BIRITIBA-MIRIM','3506607',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOA ESPERANÇA DO SUL','3506706',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOCAINA','3506805',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOFETE','3506904',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOITUVA','3507001',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOM JESUS DOS PERDÕES','3507100',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOM SUCESSO DE ITARARÉ','3507159',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BORÁ','3507209',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BORACÉIA','3507308',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BORBOREMA','3507407',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOREBI','3507456',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BOTUCATU','3507506',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BRAGANÇA PAULISTA','3507605',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BRAÚNA','3507704',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BREJO ALEGRE','3507753',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BRODÓSQUI','3507803',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BROTAS','3507902',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BURI','3508009',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BURITAMA','3508108',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('BURITIZAL','3508207',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CABRÁLIA PAULISTA','3508306',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CABREÚVA','3508405',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAÇAPAVA','3508504',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CACHOEIRA PAULISTA','3508603',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CACONDE','3508702',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAFELÂNDIA','3508801',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAIABU','3508900',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAIEIRAS','3509007',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAIUÁ','3509106',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAJAMAR','3509205',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAJATI','3509254',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAJOBI','3509304',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAJURU','3509403',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAMPINA DO MONTE ALEGRE','3509452',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAMPINAS','3509502',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAMPO LIMPO PAULISTA','3509601',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAMPOS DO JORDÃO','3509700',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAMPOS NOVOS PAULISTA','3509809',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CANANÉIA','3509908',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CANAS','3509957',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CÂNDIDO MOTA','3510005',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CÂNDIDO RODRIGUES','3510104',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CANITAR','3510153',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAPÃO BONITO','3510203',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAPELA DO ALTO','3510302',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CAPIVARI','3510401',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CARAGUATATUBA','3510500',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CARAPICUÍBA','3510609',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CARDOSO','3510708',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CASA BRANCA','3510807',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CÁSSIA DOS COQUEIROS','3510906',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CASTILHO','3511003',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CATANDUVA','3511102',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CATIGUÁ','3511201',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CEDRAL','3511300',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CERQUEIRA CÉSAR','3511409',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CERQUILHO','3511508',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CESÁRIO LANGE','3511607',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CHARQUEADA','3511706',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CHAVANTES','3557204',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CLEMENTINA','3511904',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('COLINA','3512001',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('COLÔMBIA','3512100',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CONCHAL','3512209',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CONCHAS','3512308',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CORDEIRÓPOLIS','3512407',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('COROADOS','3512506',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CORONEL MACEDO','351@id_estado05',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CORUMBATAÍ','3512704',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('COSMÓPOLIS','3512803',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('COSMORAMA','3512902',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('COTIA','3513009',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CRAVINHOS','3513108',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CRISTAIS PAULISTA','3513207',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CRUZÁLIA','3513306',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CRUZEIRO','3513405',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CUBATÃO','3513504',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('CUNHA','3513603',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DESCALVADO','3513702',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DIADEMA','3513801',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DIRCE REIS','3513850',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DIVINOLÂNDIA','3513900',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DOBRADA','3514007',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DOIS CÓRREGOS','3514106',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DOLCINÓPOLIS','3514205',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DOURADO','3514304',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DRACENA','3514403',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DUARTINA','3514502',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('DUMONT','3514601',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ECHAPORÃ','3514700',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ELDORADO','3514809',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ELIAS FAUSTO','3514908',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ELISIÁRIO','3514924',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('EMBAÚBA','3514957',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('EMBU','3515004',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('EMBU-GUAÇU','3515103',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('EMILIANÓPOLIS','3515129',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ENGENHEIRO COELHO','3515152',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ESPÍRITO SANTO DO PINHAL','3515186',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ESPÍRITO SANTO DO TURVO','3515194',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ESTIVA GERBI','3557303',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ESTRELA DO NORTE','3515301',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ESTRELA D''OESTE','3515202',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('EUCLÍDES DA CUNHA PAULISTA','3515350',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FARTURA','3515400',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FERNANDO PRESTES','3515608',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FERNANDÓPOLIS','3515509',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FERNÃO','3515657',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FERRAZ DE VASCONCELOS','3515707',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FLORA RICA','3515806',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FLOREAL','3515905',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FLÓRIDA PAULISTA','3516002',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FLORÍNIA','3516101',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FRANCA','3516200',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FRANCISCO MORATO','3516309',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('FRANCO DA ROCHA','3516408',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GABRIEL MONTEIRO','3516507',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GÁLIA','3516606',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GARÇA','3516705',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GASTÃO VIDIGAL','3516804',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GAVIÃO PEIXOTO','3516853',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GENERAL SALGADO','3516903',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GETULINA','3517000',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GLICÉRIO','3517109',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUAIÇARA','3517208',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUAIMBÊ','3517307',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUAÍRA','3517406',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUAPIAÇU','3517505',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUAPIARA','3517604',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARÁ','3517703',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARAÇAÍ','3517802',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARACI','3517901',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARANI D''OESTE','3518008',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARANTÃ','3518107',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARARAPES','3518206',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARAREMA','3518305',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARATINGUETÁ','3518404',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUAREÍ','3518503',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARIBA','3518602',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARUJÁ','3518701',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUARULHOS','3518800',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUATAPARÁ','3518859',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('GUZOLÂNDIA','3518909',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('HERCULÂNDIA','3519006',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('HOLAMBRA','3519055',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('HORTOLÂNDIA','3519071',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IACANGA','3519105',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IACRI','3519204',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IARAS','3519253',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IBATÉ','3519303',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IBIRÁ','3519402',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IBIRAREMA','3519501',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IBITINGA','3519600',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IBIÚNA','3519709',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ICÉM','3519808',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IEPÊ','3519907',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IGARAÇU DO TIETÊ','3520004',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IGARAPAVA','3520103',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IGARATÁ','3520202',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IGUAPE','3520301',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ILHA COMPRIDA','35204@id_estado',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ILHA SOLTEIRA','3520442',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ILHABELA','3520400',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('INDAIATUBA','3520509',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('INDIANA','3520608',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('INDIAPORÃ','3520707',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('INÚBIA PAULISTA','3520806',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IPAUÇU','3520905',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IPERÓ','3521002',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IPEÚNA','3521101',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IPIGUÁ','3521150',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IPORANGA','3521200',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IPUÃ','3521309',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IRACEMÁPOLIS','3521408',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IRAPUÃ','3521507',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('IRAPURU','3521606',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITABERÁ','3521705',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAÍ','3521804',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAJOBI','3521903',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAJU','3522000',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITANHAÉM','3522109',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAÓCA','3522158',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPECERICA DA SERRA','3522208',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPETININGA','3522307',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPEVA','3522406',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPEVI','3522505',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPIRA','352@id_estado04',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPIRAPUÃ PAULISTA','352@id_estado53',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITÁPOLIS','3522703',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPORANGA','3522802',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPUÍ','3522901',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAPURA','3523008',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITAQUAQUECETUBA','3523107',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITARARÉ','3523206',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITARIRI','3523305',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITATIBA','3523404',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITATINGA','3523503',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITIRAPINA','3523602',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITIRAPUÃ','3523701',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITOBI','3523800',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITU','3523909',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITUPEVA','3524006',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ITUVERAVA','3524105',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JABORANDI','3524204',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JABOTICABAL','3524303',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JACAREÍ','3524402',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JACI','3524501',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JACUPIRANGA','3524600',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JAGUARIÚNA','3524709',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JALES','3524808',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JAMBEIRO','3524907',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JANDIRA','3525003',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JARDINÓPOLIS','3525102',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JARINU','3525201',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JAÚ','3525300',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JERIQUARA','3525409',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JOANÓPOLIS','3525508',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JOÃO RAMALHO','3525607',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JOSÉ BONIFÁCIO','3525706',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JÚLIO MESQUITA','3525805',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JUMIRIM','3525854',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JUNDIAÍ','3525904',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JUNQUEIRÓPOLIS','35@id_estado001',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JUQUIÁ','35@id_estado100',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('JUQUITIBA','35@id_estado209',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LAGOINHA','35@id_estado308',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LARANJAL PAULISTA','35@id_estado407',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LAVÍNIA','35@id_estado506',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LAVRINHAS','35@id_estado605',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LEME','35@id_estado704',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LENÇÓIS PAULISTA','35@id_estado803',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LIMEIRA','35@id_estado902',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LINDÓIA','3527009',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LINS','3527108',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LORENA','3527207',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LOURDES','3527256',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LOUVEIRA','3527306',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LUCÉLIA','3527405',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LUCIANÓPOLIS','3527504',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LUÍS ANTÔNIO','3527603',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LUIZIÂNIA','3527702',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LUPÉRCIO','3527801',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('LUTÉCIA','3527900',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MACATUBA','3528007',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MACAUBAL','3528106',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MACEDÔNIA','3528205',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MAGDA','3528304',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MAIRINQUE','3528403',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MAIRIPORÃ','3528502',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MANDURI','3528601',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARABÁ PAULISTA','3528700',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARACAÍ','3528809',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARAPOAMA','3528858',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARIÁPOLIS','3528908',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARÍLIA','3529005',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARINÓPOLIS','3529104',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MARTINÓPOLIS','3529203',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MATÃO','3529302',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MAUÁ','3529401',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MENDONÇA','3529500',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MERIDIANO','3529609',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MESÓPOLIS','3529658',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIGUELÓPOLIS','3529708',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MINEIROS DO TIETÊ','3529807',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIRA ESTRELA','3530003',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIRACATU','3529906',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIRANDÓPOLIS','3530102',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIRANTE DO PARANAPANEMA','3530201',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIRASSOL','3530300',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MIRASSOLÂNDIA','3530409',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MOCOCA','3530508',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MOGI DAS CRUZES','3530607',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MOGI-GUAÇU','3530706',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MOGI-MIRIM','3530805',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MOMBUCA','3530904',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONÇÕES','3531001',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONGAGUÁ','3531100',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTE ALEGRE DO SUL','3531209',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTE ALTO','3531308',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTE APRAZÍVEL','3531407',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTE AZUL PAULISTA','3531506',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTE CASTELO','3531605',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTE MOR','3531803',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MONTEIRO LOBATO','3531704',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MORRO AGUDO','3531902',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MORUNGABA','3532009',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MOTUCA','3532058',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('MURUTINGA DO SUL','3532108',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NANTES','3532157',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NARANDIBA','3532207',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NATIVIDADE DA SERRA','3532306',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NAZARÉ PAULISTA','3532405',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NEVES PAULISTA','3532504',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NHANDEARA','353@id_estado03',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NIPOÃ','3532702',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA ALIANÇA','3532801',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA CAMPINA','3532827',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA CANAÃ PAULISTA','3532843',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA CASTILHO','3532868',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA EUROPA','3532900',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA GRANADA','3533007',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA GUATAPORANGA','3533106',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA INDEPENDÊNCIA','3533205',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA LUZITÂNIA','3533304',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVA ODESSA','3533403',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVAIS','3533254',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NOVO HORIZONTE','3533502',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('NUPORANGA','3533601',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OCAUÇU','3533700',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ÓLEO','3533809',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OLÍMPIA','3533908',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ONDA VERDE','3534005',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ORIENTE','3534104',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ORINDIÚVA','3534203',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ORLÂNDIA','3534302',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OSASCO','3534401',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OSCAR BRESSANE','3534500',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OSVALDO CRUZ','3534609',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OURINHOS','3534708',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OURO VERDE','3534807',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('OUROESTE','3534757',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PACAEMBU','3534906',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PALESTINA','3535002',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PALMARES PAULISTA','3535101',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PALMEIRA D''OESTE','3535200',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PALMITAL','3535309',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PANORAMA','3535408',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARAGUAÇU PAULISTA','3535507',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARAIBUNA','3535606',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARAÍSO','3535705',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARANAPANEMA','3535804',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARANAPUÃ','3535903',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARAPUÃ','3536000',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARDINHO','3536109',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARIQUERA-AÇU','3536208',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PARISI','3536257',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PATROCÍNIO PAULISTA','3536307',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PAULICÉIA','3536406',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PAULÍNIA','3536505',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PAULISTÂNIA','3536570',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PAULO DE FARIA','3536604',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDERNEIRAS','3536703',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDRA BELA','3536802',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDRANÓPOLIS','3536901',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDREGULHO','3537008',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDREIRA','3537107',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDRINHAS PAULISTA','3537156',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEDRO DE TOLEDO','3537206',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PENÁPOLIS','3537305',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEREIRA BARRETO','3537404',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PEREIRAS','3537503',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PERUÍBE','3537602',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIACATU','3537701',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIEDADE','3537800',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PILAR DO SUL','3537909',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PINDAMONHANGABA','3538006',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PINDORAMA','3538105',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PINHALZINHO','3538204',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIQUEROBI','3538303',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIQUETE','3538501',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRACAIA','3538600',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRACICABA','3538709',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRAJU','3538808',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRAJUÍ','3538907',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRANGI','3539004',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRAPORA DO BOM JESUS','3539103',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRAPOZINHO','3539202',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRASSUNUNGA','3539301',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PIRATININGA','3539400',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PITANGUEIRAS','3539509',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PLANALTO','3539608',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PLATINA','3539707',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('POÁ','3539806',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('POLONI','3539905',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('POMPÉIA','3540002',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PONGAÍ','3540101',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PONTAL','3540200',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PONTALINDA','3540259',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PONTES GESTAL','3540309',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('POPULINA','3540408',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PORANGABA','3540507',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PORTO FELIZ','3540606',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PORTO FERREIRA','3540705',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('POTIM','3540754',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('POTIRENDABA','3540804',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRACINHA','3540853',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRADÓPOLIS','3540903',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRAIA GRANDE','3541000',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRATÂNIA','3541059',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRESIDENTE ALVES','3541109',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRESIDENTE BERNARDES','3541208',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRESIDENTE EPITÁCIO','3541307',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRESIDENTE PRUDENTE','3541406',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PRESIDENTE VENCESLAU','3541505',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('PROMISSÃO','3541604',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('QUADRA','3541653',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('QUATÁ','3541703',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('QUEIROZ','3541802',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('QUELUZ','3541901',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('QUINTANA','3542008',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RAFARD','3542107',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RANCHARIA','3542206',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('REDENÇÃO DA SERRA','3542305',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('REGENTE FEIJÓ','3542404',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('REGINÓPOLIS','3542503',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('REGISTRO','354@id_estado02',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RESTINGA','3542701',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRA','3542800',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO BONITO','3542909',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO BRANCO','3543006',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO CORRENTE','3543105',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO DO SUL','3543204',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO DOS ÍNDIOS','3543238',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO GRANDE','3543253',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO PIRES','3543303',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIBEIRÃO PRETO','3543402',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIFAINA','3543600',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RINCÃO','3543709',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RINÓPOLIS','3543808',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIO CLARO','3543907',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIO DAS PEDRAS','3544004',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIO GRANDE DA SERRA','3544103',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIOLÂNDIA','3544202',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RIVERSUL','3543501',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ROSANA','3544251',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ROSEIRA','3544301',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RUBIÁCEA','3544400',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('RUBINÉIA','3544509',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SABINO','3544608',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SAGRES','3544707',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALES','3544806',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALES OLIVEIRA','3544905',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALESÓPOLIS','3545001',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALMOURÃO','3545100',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALTINHO','3545159',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALTO','3545209',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALTO DE PIRAPORA','3545308',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SALTO GRANDE','3545407',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANDOVALINA','3545506',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA ADÉLIA','3545605',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA ALBERTINA','3545704',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA BARBARA D''OESTE','3545803',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA BRANCA','3546009',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA CLARA D''OESTE','3546108',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA CRUZ DA CONCEIÇÃO','3546207',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA CRUZ DA ESPERANÇA','3546256',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA CRUZ DAS PALMEIRAS','3546306',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA CRUZ DO RIO PARDO','3546405',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA ERNESTINA','3546504',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA FÉ DO SUL','3546603',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA GERTRUDES','3546702',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA ISABEL','3546801',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA LÚCIA','3546900',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA MARIA DA SERRA','3547007',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA MERCEDES','3547106',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA RITA DO PASSA QUATRO','3547502',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA RITA D''OESTE','3547403',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA ROSA DO VITERBO','3547601',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTA SALETE','3547650',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTANA DA PONTE PENSA','3547205',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTANA DO PARNAÍBA','3547304',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANASTÁCIO','3547700',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANDRÉ','3547809',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANTÔNIO DA ALEGRIA','3547908',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANTÔNIO DE POSSE','3548005',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANTÔNIO DO ARACANGUÁ','3548054',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANTÔNIO DO JARDIM','3548104',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO ANTÔNIO DO PINHAL','3548203',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTO EXPEDITO','3548302',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTÓPOLIS DO AGUAPEÍ','3548401',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SANTOS','3548500',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO BENTO DO SAPUCAÍ','3548609',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO BERNARDO DO CAMPO','3548708',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO CAETANO DO SUL','3548807',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO CARLOS','3548906',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO FRANCISCO','3549003',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOÃO DA BOA VISTA','3549102',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOÃO DAS DUAS PONTES','3549201',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOÃO DE IRACEMA','3549250',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SAO JOAO DO PAU D''ALHO','3549300',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOAQUIM DA BARRA','3549409',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOSÉ DA BELA VISTA','3549508',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOSÉ DO BARREIRO','3549607',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOSÉ DO RIO PARDO','3549706',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOSÉ DO RIO PRETO','3549805',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO JOSÉ DOS CAMPOS','3549904',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO LOURENÇO DA SERRA','3549953',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO LUÍS DO PARAITINGA','3550001',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO MANUEL','3550100',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO MIGUEL ARCANJO','3550209',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO PAULO','3550308',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO PEDRO','3550407',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO PEDRO DO TURVO','3550506',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO ROQUE','3550605',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO SEBASTIÃO','3550704',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO SEBASTIÃO DA GRAMA','3550803',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO SIMÃO','3550902',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SÃO VICENTE','3551009',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SARAPUÍ','3551108',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SARUTAIÁ','3551207',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SEBASTIANÓPOLIS DO SUL','3551306',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SERRA AZUL','3551405',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SERRA NEGRA','3551603',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SERRANA','3551504',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SERTÃOZINHO','3551702',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SETE BARRAS','3551801',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SEVERÍNIA','3551900',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SILVEIRAS','3552007',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SOCORRO','3552106',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SOROCABA','3552205',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SUD MENNUCCI','3552304',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SUMARÉ','3552403',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SUZANÁPOLIS','3552551',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('SUZANO','3552502',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TABAPUÃ','355@id_estado01',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TABATINGA','3552700',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TABOÃO DA SERRA','3552809',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TACIBA','3552908',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAGUAÍ','3553005',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAIAÇU','3553104',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAIÚVA','3553203',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAMBAÚ','3553302',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TANABI','3553401',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAPIRAÍ','3553500',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAPIRATIBA','3553609',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAQUARAL','3553658',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAQUARITINGA','3553708',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAQUARITUBA','3553807',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAQUARIVAÍ','3553856',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TARABAÍ','3553906',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TARUMÃ','3553955',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TATUÍ','3554003',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TAUBATÉ','3554102',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TEJUPÁ','3554201',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TEODORO SAMPAIO','3554300',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TERRA ROXA','3554409',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TIETÊ','3554508',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TIMBURI','3554607',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TORRE DE PEDRA','3554656',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TORRINHA','3554706',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TRABIJU','3554755',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TREMEMBÉ','3554805',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TRÊS FRONTEIRAS','3554904',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TUIUTI','3554953',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TUPÃ','3555000',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TUPI PAULISTA','3555109',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TURIÚBA','3555208',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('TURMALINA','3555307',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('UBARANA','3555356',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('UBATUBA','3555406',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('UBIRAJARA','3555505',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('UCHOA','3555604',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('UNIÃO PAULISTA','3555703',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('URÂNIA','3555802',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('URU','3555901',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('URUPÊS','3556008',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VALENTIM GENTIL','3556107',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VALINHOS','3556206',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VALPARAÍSO','3556305',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VARGEM','3556354',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VARGEM GRANDE DO SUL','3556404',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VARGEM GRANDE PAULISTA','3556453',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VÁRZEA PAULISTA','3556503',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VERA CRUZ','3556602',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VINHEDO','3556701',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VIRADOURO','3556800',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VISTA ALEGRE DO ALTO','3556909',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VITÓRIA BRASIL','3556958',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VOTORANTIM','3557006',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('VOTUPORANGA','3557105',@id_estado)
insert into cidade (nome, codigo_ibge, id_estado) values ('ZACARIAS','3557154',@id_estado)
