insert into tipo_logradouro (sigla, descricao) values ('A','Área')
insert into tipo_logradouro (sigla, descricao) values ('AC','Acesso')
insert into tipo_logradouro (sigla, descricao) values ('ACA','Acampamento')
insert into tipo_logradouro (sigla, descricao) values ('ACL','Acesso Local')
insert into tipo_logradouro (sigla, descricao) values ('AD','Adro')
insert into tipo_logradouro (sigla, descricao) values ('AE','Área Especial')
insert into tipo_logradouro (sigla, descricao) values ('AER','Aeroporto')
insert into tipo_logradouro (sigla, descricao) values ('AL','Alameda')
insert into tipo_logradouro (sigla, descricao) values ('AMD','Avenida Marginal Direita')
insert into tipo_logradouro (sigla, descricao) values ('AME','Avenida Marginal Esquerda')
insert into tipo_logradouro (sigla, descricao) values ('AN','Anel Viário')
insert into tipo_logradouro (sigla, descricao) values ('ANT','Antiga Estrada')
insert into tipo_logradouro (sigla, descricao) values ('ART','Artéria')
insert into tipo_logradouro (sigla, descricao) values ('AT','Alto')
insert into tipo_logradouro (sigla, descricao) values ('ATL','Atalho')
insert into tipo_logradouro (sigla, descricao) values ('A V','Área Verde')
insert into tipo_logradouro (sigla, descricao) values ('AV','Avenida')
insert into tipo_logradouro (sigla, descricao) values ('AVC','Avenida Contorno')
insert into tipo_logradouro (sigla, descricao) values ('AVM','Avenida Marginal')
insert into tipo_logradouro (sigla, descricao) values ('AVV','Avenida Velha')
insert into tipo_logradouro (sigla, descricao) values ('BAL','Balneário')
insert into tipo_logradouro (sigla, descricao) values ('BC','Beco')
insert into tipo_logradouro (sigla, descricao) values ('BCO','Buraco')
insert into tipo_logradouro (sigla, descricao) values ('BEL','Belvedere')
insert into tipo_logradouro (sigla, descricao) values ('BL','Bloco')
insert into tipo_logradouro (sigla, descricao) values ('BLO','Balão')
insert into tipo_logradouro (sigla, descricao) values ('BLS','Blocos')
insert into tipo_logradouro (sigla, descricao) values ('BLV','Bulevar')
insert into tipo_logradouro (sigla, descricao) values ('BSQ','Bosque')
insert into tipo_logradouro (sigla, descricao) values ('BVD','Boulevard')
insert into tipo_logradouro (sigla, descricao) values ('BX','Baixa')
insert into tipo_logradouro (sigla, descricao) values ('C','Cais')
insert into tipo_logradouro (sigla, descricao) values ('CAL','Calçada')
insert into tipo_logradouro (sigla, descricao) values ('CAM','Caminho')
insert into tipo_logradouro (sigla, descricao) values ('CAN','Canal')
insert into tipo_logradouro (sigla, descricao) values ('CH','Chácara')
insert into tipo_logradouro (sigla, descricao) values ('CHA','Chapadão')
insert into tipo_logradouro (sigla, descricao) values ('CIC','Ciclovia')
insert into tipo_logradouro (sigla, descricao) values ('CIR','Circular')
insert into tipo_logradouro (sigla, descricao) values ('CJ','Conjunto')
insert into tipo_logradouro (sigla, descricao) values ('CJM','Conjunto Mutirão')
insert into tipo_logradouro (sigla, descricao) values ('CMP','Complexo Viário')
insert into tipo_logradouro (sigla, descricao) values ('COL','Colônia')
insert into tipo_logradouro (sigla, descricao) values ('COM','Comunidade')
insert into tipo_logradouro (sigla, descricao) values ('CON','Condomínio')
insert into tipo_logradouro (sigla, descricao) values ('COR','Corredor')
insert into tipo_logradouro (sigla, descricao) values ('CPO','Campo')
insert into tipo_logradouro (sigla, descricao) values ('CRG','Córrego')
insert into tipo_logradouro (sigla, descricao) values ('CTN','Contorno')
insert into tipo_logradouro (sigla, descricao) values ('DSC','Descida')
insert into tipo_logradouro (sigla, descricao) values ('DSV','Desvio')
insert into tipo_logradouro (sigla, descricao) values ('DT','Distrito')
insert into tipo_logradouro (sigla, descricao) values ('EB','Entre Bloco')
insert into tipo_logradouro (sigla, descricao) values ('EIM','Estrada Intermunicipal')
insert into tipo_logradouro (sigla, descricao) values ('ENS','Enseada')
insert into tipo_logradouro (sigla, descricao) values ('ENT','Entrada Particular')
insert into tipo_logradouro (sigla, descricao) values ('EQ','Entre Quadra')
insert into tipo_logradouro (sigla, descricao) values ('ESC','Escada')
insert into tipo_logradouro (sigla, descricao) values ('ESD','Escadaria')
insert into tipo_logradouro (sigla, descricao) values ('ESE','Estrada Estadual')
insert into tipo_logradouro (sigla, descricao) values ('ESI','Estrada Vicinal')
insert into tipo_logradouro (sigla, descricao) values ('ESL','Estrada de Ligação')
insert into tipo_logradouro (sigla, descricao) values ('ESM','Estrada Municipal')
insert into tipo_logradouro (sigla, descricao) values ('ESP','Esplanada')
insert into tipo_logradouro (sigla, descricao) values ('ESS','Estrada de Servidão')
insert into tipo_logradouro (sigla, descricao) values ('EST','Estrada')
insert into tipo_logradouro (sigla, descricao) values ('ESV','Estrada Velha')
insert into tipo_logradouro (sigla, descricao) values ('ETA','Estrada Antiga')
insert into tipo_logradouro (sigla, descricao) values ('ETC','Estação')
insert into tipo_logradouro (sigla, descricao) values ('ETD','Estádio')
insert into tipo_logradouro (sigla, descricao) values ('ETN','Estância')
insert into tipo_logradouro (sigla, descricao) values ('ETP','Estrada Particular')
insert into tipo_logradouro (sigla, descricao) values ('ETT','Estacionamento')
insert into tipo_logradouro (sigla, descricao) values ('EVA','Evangélica')
insert into tipo_logradouro (sigla, descricao) values ('EVD','Elevada')
insert into tipo_logradouro (sigla, descricao) values ('EX','Eixo Industrial')
insert into tipo_logradouro (sigla, descricao) values ('FAV','Favela')
insert into tipo_logradouro (sigla, descricao) values ('FAZ','Fazenda')
insert into tipo_logradouro (sigla, descricao) values ('FER','Ferrovia')
insert into tipo_logradouro (sigla, descricao) values ('FNT','Fonte')
insert into tipo_logradouro (sigla, descricao) values ('FRA','Feira')
insert into tipo_logradouro (sigla, descricao) values ('FTE','Forte')
insert into tipo_logradouro (sigla, descricao) values ('GAL','Galeria')
insert into tipo_logradouro (sigla, descricao) values ('GJA','Granja')
insert into tipo_logradouro (sigla, descricao) values ('HAB','Núcleo Habitacional')
insert into tipo_logradouro (sigla, descricao) values ('IA','Ilha')
insert into tipo_logradouro (sigla, descricao) values ('IND','Indeterminado')
insert into tipo_logradouro (sigla, descricao) values ('IOA','Ilhota')
insert into tipo_logradouro (sigla, descricao) values ('JD','Jardim')
insert into tipo_logradouro (sigla, descricao) values ('JDE','Jardinete')
insert into tipo_logradouro (sigla, descricao) values ('LD','Ladeira')
insert into tipo_logradouro (sigla, descricao) values ('LGA','Lagoa')
insert into tipo_logradouro (sigla, descricao) values ('LGO','Lago')
insert into tipo_logradouro (sigla, descricao) values ('LOT','Loteamento')
insert into tipo_logradouro (sigla, descricao) values ('LRG','Largo')
insert into tipo_logradouro (sigla, descricao) values ('LT','Lote')
insert into tipo_logradouro (sigla, descricao) values ('MER','Mercado')
insert into tipo_logradouro (sigla, descricao) values ('MNA','Marina')
insert into tipo_logradouro (sigla, descricao) values ('MOD','Modulo')
insert into tipo_logradouro (sigla, descricao) values ('MRG','Projeção')
insert into tipo_logradouro (sigla, descricao) values ('MRO','Morro')
insert into tipo_logradouro (sigla, descricao) values ('MTE','Monte')
insert into tipo_logradouro (sigla, descricao) values ('NUC','Núcleo')
insert into tipo_logradouro (sigla, descricao) values ('NUR','Núcleo Rural')
insert into tipo_logradouro (sigla, descricao) values ('OUT','Outeiro')
insert into tipo_logradouro (sigla, descricao) values ('PAR','Paralela')
insert into tipo_logradouro (sigla, descricao) values ('PAS','Passeio')
insert into tipo_logradouro (sigla, descricao) values ('PAT','Pátio')
insert into tipo_logradouro (sigla, descricao) values ('PC','Praça')
insert into tipo_logradouro (sigla, descricao) values ('PCE','Praça de Esportes')
insert into tipo_logradouro (sigla, descricao) values ('PDA','Parada')
insert into tipo_logradouro (sigla, descricao) values ('PDO','Paradouro')
insert into tipo_logradouro (sigla, descricao) values ('PNT','Ponta')
insert into tipo_logradouro (sigla, descricao) values ('PR','Praia')
insert into tipo_logradouro (sigla, descricao) values ('PRL','Prolongamento')
insert into tipo_logradouro (sigla, descricao) values ('PRM','Parque Municipal')
insert into tipo_logradouro (sigla, descricao) values ('PRQ','Parque')
insert into tipo_logradouro (sigla, descricao) values ('PRR','Parque Residencial')
insert into tipo_logradouro (sigla, descricao) values ('PSA','Passarela')
insert into tipo_logradouro (sigla, descricao) values ('PSG','Passagem')
insert into tipo_logradouro (sigla, descricao) values ('PSP','Passagem de Pedestre')
insert into tipo_logradouro (sigla, descricao) values ('PSS','Passagem Subterrânea')
insert into tipo_logradouro (sigla, descricao) values ('PTE','Ponte')
insert into tipo_logradouro (sigla, descricao) values ('PTO','Porto')
insert into tipo_logradouro (sigla, descricao) values ('Q','Quadra')
insert into tipo_logradouro (sigla, descricao) values ('QTA','Quinta')
insert into tipo_logradouro (sigla, descricao) values ('QTS','Quintas')
insert into tipo_logradouro (sigla, descricao) values ('R','Rua')
insert into tipo_logradouro (sigla, descricao) values ('R I','Rua Integração')
insert into tipo_logradouro (sigla, descricao) values ('R L','Rua de Ligação')
insert into tipo_logradouro (sigla, descricao) values ('R P','Rua Particular')
insert into tipo_logradouro (sigla, descricao) values ('R V','Rua Velha')
insert into tipo_logradouro (sigla, descricao) values ('RAM','Ramal')
insert into tipo_logradouro (sigla, descricao) values ('RCR','Recreio')
insert into tipo_logradouro (sigla, descricao) values ('REC','Recanto')
insert into tipo_logradouro (sigla, descricao) values ('RER','Retiro')
insert into tipo_logradouro (sigla, descricao) values ('RES','Residencial')
insert into tipo_logradouro (sigla, descricao) values ('RET','Reta')
insert into tipo_logradouro (sigla, descricao) values ('RLA','Ruela')
insert into tipo_logradouro (sigla, descricao) values ('RMP','Rampa')
insert into tipo_logradouro (sigla, descricao) values ('ROA','Rodo Anel')
insert into tipo_logradouro (sigla, descricao) values ('ROD','Rodovia')
insert into tipo_logradouro (sigla, descricao) values ('ROT','Rotula')
insert into tipo_logradouro (sigla, descricao) values ('RPE','Rua de Pedestre')
insert into tipo_logradouro (sigla, descricao) values ('RPR','Margem')
insert into tipo_logradouro (sigla, descricao) values ('RTN','Retorno')
insert into tipo_logradouro (sigla, descricao) values ('RTT','Rotatória')
insert into tipo_logradouro (sigla, descricao) values ('SEG','Segunda Avenida')
insert into tipo_logradouro (sigla, descricao) values ('SIT','Sitio')
insert into tipo_logradouro (sigla, descricao) values ('SRV','Servidão')
insert into tipo_logradouro (sigla, descricao) values ('ST','Setor')
insert into tipo_logradouro (sigla, descricao) values ('SUB','Subida')
insert into tipo_logradouro (sigla, descricao) values ('TCH','Trincheira')
insert into tipo_logradouro (sigla, descricao) values ('TER','Terminal')
insert into tipo_logradouro (sigla, descricao) values ('TR','Trecho')
insert into tipo_logradouro (sigla, descricao) values ('TRV','Trevo')
insert into tipo_logradouro (sigla, descricao) values ('TUN','Túnel')
insert into tipo_logradouro (sigla, descricao) values ('TV','Travessa')
insert into tipo_logradouro (sigla, descricao) values ('TVP','Travessa Particular')
insert into tipo_logradouro (sigla, descricao) values ('TVV','Travessa Velha')
insert into tipo_logradouro (sigla, descricao) values ('UNI','Unidade')
insert into tipo_logradouro (sigla, descricao) values ('V','Via')
insert into tipo_logradouro (sigla, descricao) values ('V C','Via Coletora')
insert into tipo_logradouro (sigla, descricao) values ('V L','Via Local')
insert into tipo_logradouro (sigla, descricao) values ('VAC','Via de Acesso')
insert into tipo_logradouro (sigla, descricao) values ('VAL','Vala')
insert into tipo_logradouro (sigla, descricao) values ('VCO','Via Costeira')
insert into tipo_logradouro (sigla, descricao) values ('VD','Viaduto')
insert into tipo_logradouro (sigla, descricao) values ('V-E','Via Expressa')
insert into tipo_logradouro (sigla, descricao) values ('VER','Vereda')
insert into tipo_logradouro (sigla, descricao) values ('VEV','Via Elevado')
insert into tipo_logradouro (sigla, descricao) values ('VL','Vila')
insert into tipo_logradouro (sigla, descricao) values ('VLA','Viela')
insert into tipo_logradouro (sigla, descricao) values ('VLE','Vale')
insert into tipo_logradouro (sigla, descricao) values ('VLT','Via Litorânea')
insert into tipo_logradouro (sigla, descricao) values ('VPE','Via de Pedestre')
insert into tipo_logradouro (sigla, descricao) values ('VRT','Variante')
insert into tipo_logradouro (sigla, descricao) values ('ZIG','Zigue-Zague')
