//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoFullStack.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoFullStack.Util.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é inválido.
        /// </summary>
        public static string Erro_CEPInvalido {
            get {
                return ResourceManager.GetString("Erro_CEPInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP deve conter somente números.
        /// </summary>
        public static string Erro_CEPSomenteNumeros {
            get {
                return ResourceManager.GetString("Erro_CEPSomenteNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do IBGE é inválido.
        /// </summary>
        public static string Erro_CodigoIBGEInvalido {
            get {
                return ResourceManager.GetString("Erro_CodigoIBGEInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da descrição é Invalida.
        /// </summary>
        public static string Erro_DescricaoInvalida {
            get {
                return ResourceManager.GetString("Erro_DescricaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ser vazia.
        /// </summary>
        public static string Erro_DescricaoVazia {
            get {
                return ResourceManager.GetString("Erro_DescricaoVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do Bairro é inválido.
        /// </summary>
        public static string Erro_IDBairroInvalido {
            get {
                return ResourceManager.GetString("Erro_IDBairroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código da Cidade é inválido.
        /// </summary>
        public static string Erro_IDCidadeInvalido {
            get {
                return ResourceManager.GetString("Erro_IDCidadeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do Estado é inválido.
        /// </summary>
        public static string Erro_IDEstadoInvalido {
            get {
                return ResourceManager.GetString("Erro_IDEstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do Pais é inválido.
        /// </summary>
        public static string Erro_IDPaisInvalido {
            get {
                return ResourceManager.GetString("Erro_IDPaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do Pais não pode ser vazio.
        /// </summary>
        public static string Erro_IDPaisVazio {
            get {
                return ResourceManager.GetString("Erro_IDPaisVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Códgio da Rua é invalido.
        /// </summary>
        public static string Erro_IDRuaInvalido {
            get {
                return ResourceManager.GetString("Erro_IDRuaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código do Tipo de Logradouro é inválido.
        /// </summary>
        public static string Erro_IDTipoLogradouroInvalido {
            get {
                return ResourceManager.GetString("Erro_IDTipoLogradouroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do nome é Invalido.
        /// </summary>
        public static string Erro_NomeInvalido {
            get {
                return ResourceManager.GetString("Erro_NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do nome não pode ser vazio.
        /// </summary>
        public static string Erro_NomeVazio {
            get {
                return ResourceManager.GetString("Erro_NomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Final não pode ser menor que o Número Inicial.
        /// </summary>
        public static string Erro_RuaCepNumeroFinalMenor {
            get {
                return ResourceManager.GetString("Erro_RuaCepNumeroFinalMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Inicial não pode ser igual ao Número Final.
        /// </summary>
        public static string Erro_RuaCepNumeroInicialIgual {
            get {
                return ResourceManager.GetString("Erro_RuaCepNumeroInicialIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Inicial não pode ser vazio.
        /// </summary>
        public static string Erro_RuaCepNumeroInicialVazio {
            get {
                return ResourceManager.GetString("Erro_RuaCepNumeroInicialVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla do Estado é inválida.
        /// </summary>
        public static string Erro_SiglaEstadoInvalida {
            get {
                return ResourceManager.GetString("Erro_SiglaEstadoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla do Estado não pode ser vazia.
        /// </summary>
        public static string Erro_SiglaEstadoVazia {
            get {
                return ResourceManager.GetString("Erro_SiglaEstadoVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla do Pais é inválida.
        /// </summary>
        public static string Erro_SiglaPaisInvalida {
            get {
                return ResourceManager.GetString("Erro_SiglaPaisInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sigla do Pais não pode ser vazia.
        /// </summary>
        public static string Erro_SiglaPaisVazia {
            get {
                return ResourceManager.GetString("Erro_SiglaPaisVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla do Tipo de Logradouro é inválida.
        /// </summary>
        public static string Erro_SiglaTipoLogradouroInvalida {
            get {
                return ResourceManager.GetString("Erro_SiglaTipoLogradouroInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Inválido.
        /// </summary>
        public static string Erro_UsuarioEmailInvalido {
            get {
                return ResourceManager.GetString("Erro_UsuarioEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Inativo.
        /// </summary>
        public static string Erro_UsuarioInativo {
            get {
                return ResourceManager.GetString("Erro_UsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário Não Encontrado.
        /// </summary>
        public static string Erro_UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Inválida.
        /// </summary>
        public static string Erro_UsuarioSenhaInvalida {
            get {
                return ResourceManager.GetString("Erro_UsuarioSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas são diferentes.
        /// </summary>
        public static string Erro_UsuarioSenhasDiferentes {
            get {
                return ResourceManager.GetString("Erro_UsuarioSenhasDiferentes", resourceCulture);
            }
        }
    }
}
